// src/pages/SubmitAttempt.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { photosApi } from '../api/photos'
import ImageUpload from '../components/ImageUpload.vue'

const route = useRoute()
const router = useRouter()
const photoId = Number(route.params.id)

const imageFile = ref<File | null>(null)
const guessedLocation = ref('')
const error = ref('')
const submitting = ref(false)

async function handleSubmit() {
  error.value = ''
  if (!imageFile.value) { error.value = '请上传匹配照片'; return }
  if (!guessedLocation.value.trim()) { error.value = '请描述你猜测的地点'; return }
  submitting.value = true
  try {
    const res = await photosApi.submitAttempt(photoId, {
      image: imageFile.value,
      guessed_location: guessedLocation.value.trim(),
    })
    if (res.data.success) {
      alert(res.data.data.message)
      router.push(`/photos/${photoId}`)
    }
  } catch (err: unknown) {
    const data = err as { message?: string; code?: number }
    if (data.code === 5) {
      error.value = '你已有待审核的答题记录，请等待审核结果'
    } else {
      error.value = data.message || '提交失败'
    }
  } finally {
    submitting.value = false
  }
}
</script>

<template>
  <div class="max-w-lg mx-auto">
    <h1 class="text-2xl font-bold text-text mb-2">提交答案</h1>
    <p class="text-sm text-text-light mb-6">请在上传图片的<strong>同一地点、同一角度</strong>拍摄照片作为验证</p>

    <form @submit.prevent="handleSubmit" class="bg-card rounded-xl p-6 border border-border space-y-5">
      <div v-if="error" class="bg-red-50 text-accent text-sm p-3 rounded-lg">{{ error }}</div>

      <ImageUpload @select="(f: File) => imageFile = f" label="上传匹配照片" hint="请在同一地点同一角度拍摄" />

      <div>
        <label class="block text-sm font-medium text-text mb-1">猜测的地点 <span class="text-accent">*</span></label>
        <input v-model="guessedLocation" type="text" class="w-full px-3 py-2.5 rounded-lg border border-border bg-bg focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition-colors" placeholder="如：主楼A座5楼东侧窗台" />
      </div>

      <button type="submit" :disabled="submitting" class="w-full py-2.5 rounded-lg bg-primary text-white font-medium hover:bg-primary-light disabled:opacity-50 transition-colors">
        {{ submitting ? '提交中...' : '提交答案' }}
      </button>
    </form>
  </div>
</template>

// src/pages/SubmitAttempt.tsx
import { useState, type FormEvent } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { photosApi } from '../api/photos';
import { ImageUpload } from '../components/ImageUpload';

export default function SubmitAttempt() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const photoId = Number(id);

  const [imageFile, setImageFile] = useState<File | null>(null);
  const [guessedLocation, setGuessedLocation] = useState('');
  const [error, setError] = useState('');
  const [submitting, setSubmitting] = useState(false);

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    setError('');
    if (!imageFile) {
      setError('请上传匹配照片');
      return;
    }
    if (!guessedLocation.trim()) {
      setError('请描述你猜测的地点');
      return;
    }
    setSubmitting(true);
    try {
      const res = await photosApi.submitAttempt(photoId, {
        image: imageFile,
        guessed_location: guessedLocation.trim(),
      });
      if (res.data.success) {
        alert(res.data.data.message);
        navigate(`/photos/${photoId}`);
      }
    } catch (err: unknown) {
      const data = (err as { message?: string; code?: number });
      if (data.code === 5) {
        setError('你已有待审核的答题记录，请等待审核结果');
      } else {
        setError(data.message || '提交失败');
      }
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="max-w-lg mx-auto">
      <h1 className="text-2xl font-bold text-text mb-2">提交答案</h1>
      <p className="text-sm text-text-light mb-6">
        请在上传图片的<strong>同一地点、同一角度</strong>拍摄照片作为验证
      </p>

      <form onSubmit={handleSubmit} className="bg-card rounded-xl p-6 border border-border space-y-5">
        {error && (
          <div className="bg-red-50 text-accent text-sm p-3 rounded-lg">{error}</div>
        )}

        <ImageUpload
          onFileSelect={setImageFile}
          label="上传匹配照片"
          hint="请在同一地点同一角度拍摄"
        />

        <div>
          <label className="block text-sm font-medium text-text mb-1">
            猜测的地点 <span className="text-accent">*</span>
          </label>
          <input
            type="text"
            value={guessedLocation}
            onChange={(e) => setGuessedLocation(e.target.value)}
            className="w-full px-3 py-2.5 rounded-lg border border-border bg-bg focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition-colors"
            placeholder="如：主楼A座5楼东侧窗台"
          />
        </div>

        <button
          type="submit"
          disabled={submitting}
          className="w-full py-2.5 rounded-lg bg-primary text-white font-medium hover:bg-primary-light disabled:opacity-50 transition-colors"
        >
          {submitting ? '提交中...' : '提交答案'}
        </button>
      </form>
    </div>
  );
}
