// src/components/Empty.tsx
interface EmptyProps {
  icon?: string;
  title?: string;
  description?: string;
  action?: React.ReactNode;
}

export function Empty({
  icon = '📭',
  title = '暂无内容',
  description = '',
  action,
}: EmptyProps) {
  return (
    <div className="flex flex-col items-center justify-center py-20 text-center">
      <span className="text-5xl mb-4">{icon}</span>
      <h3 className="text-lg font-medium text-text mb-1">{title}</h3>
      {description && (
        <p className="text-sm text-text-light max-w-sm">{description}</p>
      )}
      {action && <div className="mt-4">{action}</div>}
    </div>
  );
}

// src/components/Empty.vue
<script setup lang="ts">
defineProps<{
  icon?: string
  title?: string
  description?: string
}>()
</script>

<template>
  <div class="flex flex-col items-center justify-center py-20 text-center">
    <span class="text-5xl mb-4">{{ icon ?? '📭' }}</span>
    <h3 class="text-lg font-medium text-text mb-1">{{ title ?? '暂无内容' }}</h3>
    <p v-if="description" class="text-sm text-text-light max-w-sm">{{ description }}</p>
    <div v-if="$slots.action" class="mt-4"><slot name="action" /></div>
  </div>
</template>
